name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}, python ${{ matrix.python }}
    strategy:
      matrix:
        java: [8, 11, 17]
        python: ['3.8', '3.11', '3.12']

        exclude:
          - java: 8
            python: '3.11'
          - java: 8
            python: '3.12'
          - java: 11
            python: '3.8'
          - java: 11
            python: '3.12'
          - java: 17
            python: '3.8'
          - java: 17
            python: '3.11'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: |
          chmod +x gradlew
          python --version
          pip --version
          ./gradlew assemble --no-daemon

      - name: Test
        env:
          GH_ACTIONS: true
        run: ./gradlew check --no-daemon

      - name: Build coverage report
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: ./gradlew jacocoTestReport --no-daemon

      - uses: codecov/codecov-action@v4
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: LINUX
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}